### ISSUE TITLE
README issues.

### ISSUE THREAD

**Issue by WZinda** [aws/credentials-fetcher#16]
After viewing [this blog post from AWS](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-open-sourced-credentials-fetcher-simplify-microsoft-ad-access-linux-containers/), I came to this repository in order to setup GMSA for Linux containers in AWS ECS. I have had a few problems so far:

1.  The README states that credentials-fetcher can be installed onto Amazon Linux 2022 via `sudo yum install credentials-fetcher`. This is seems incorrect, given that Amazon Linux 2022 uses `dnf`, not `yum`, and also that the package isn't available to `dnf`. Amazon Linux 2 uses `yum`, and this package isn't available there either.
2. There are several places in the code that use the `realm` command, which is provided by the `realmd` package. The `realmd` package is unavailable in Amazon Linux 2022, removed  [as per this release documentation from AWS](https://docs.aws.amazon.com/linux/al2022/release-notes/removed-packages-al2022.html). How is this expected to work in Amazon Linux 2022? I'm assuming that this is actually expected to work on Amazon Linux 2.
4. How is this service expected to be invoked and provide the resulting tickets to a given container? Is the expectation that all containers mount the ticket output directory? If using docker with the credentialspec option, does it invoke this service? How is this usable from an ECS perspective?

Any help or guidance will be greatly appreciated.

**Comment by saikiranakula-amzn** [comment]
Thank you for reaching out,
1. As of today the credentials-fetcher is on the path of getting released for AL2022, we can provide you update on this as the release goes out.
2. For the realmd package, we had a plan to release it part of AL2022 by the end of this month
3. For the ECS use case, The credspec info is passed to ECS as part of task definition. Agent will create application container with bind mounts to the kerberos ticket files, which are created for the corresponding gMSA service accounts as needed. Currently we don't support docker api credentialspec option.  

You can follow the local set up from scratch setup to explore the daemon more, we will provide you updates as soon we release for AL2022 and have ECS integration release

**Comment by smhmhmd** [comment]
We need to keep the README current, we will fix this.

**Comment by smhmhmd** [comment]
Fixed in https://github.com/aws/credentials-fetcher/commit/e952f4a47db2d4985026e1fd21f4a630da8e0cec

**Comment by WZinda** [comment]
@saikiranakula-amzn In particular on point 3

>  For the ECS use case, The credspec info is passed to ECS as part of task definition. Agent will create application container with bind mounts to the kerberos ticket files, which are created for the corresponding gMSA service accounts as needed. Currently we don't support docker api credentialspec option.

Where in the task definition would I pass in the credentialspec to get the ECS Agent do what you described above?

**Comment by saikiranakula-amzn** [comment]
we can store the credspec in either parameterstore/s3. Pass the arn to the task definition in dockersecurityopt field, same as how we pass it for windows gMSA. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows-gmsa.html
