### ISSUE TITLE
Need option to have krb5cc files also written to /var/credentials-fetcher/krbdir/ in format of krb5cc_%{uid}

### ISSUE THREAD

**Issue by sega19** [aws/credentials-fetcher#61]
I'm want to use Credentials-Fetcher in combination with SMB CSI Driver for Kubernetes
https://github.com/kubernetes-csi/csi-driver-smb. Mounting takes place at the worker node level, not inside the pod/container.
That driver currently has no support for pulling updated tickets stored as kubernetes secrets nor refreshing them.
Because of that, I want to use credentials-fetcher to obtain and refresh the kerberos tickets.

To make both work together, I will let the driver go thru its normal process of writing to the hard coded path of 
/var/lib/kubelet/kerberos/ 
but the file it writes into that location (ex: krb5_1000) does not need to be a valid ticket because
/etc/krb5.conf.d/ccache.conf will be configured to point to the credentials-fetcher path of 
/var/credentials-fetcher/krbdir/ instead.

As long as credentials-fetcher continues to write into its lease folder structure AND puts a file directly into 
/var/credentials-fetcher/krbdir (ex: /var/credentials-fetcher/krbdir/krb5cc_1000), then the mount cifs command will find the valid/refreshed Kerberos ticket and mount.

Note: UID needs to be in the file's name, unlike in the lease subfolders. Ex: krb5_1000, krb5_1001, etc.

Note: I think mechanism could also work for Amazon ECS for mounting CIFS(SMB).

**Comment by jamolina** [comment]
@smhmhmd is working on this

**Comment by smhmhmd** [comment]
This is part of the PR - https://github.com/aws/credentials-fetcher/pull/53

**Comment by saikiranakula-amzn** [comment]
closing this issue, as this is not needed anymore
