### ISSUE TITLE
Ticket Expiration  vs Renewal Expiration 

### ISSUE THREAD

**Issue by fordth** [aws/credentials-fetcher#67]
krb.cpp is_ticket_ready_for_renewal() only checks if the ticket renewal expiration is within an hour.  I believe the default behavior is the ticket renewal expiration is ~8 days after the actual ticket expiration.  This would cause an expired ticket not to be refreshed and possibly provide consumers an expired ticket, since the ticket expired but the refresh expiration has days left.  My fork contains a branch that has this fix (The method in my branch is called get_ticket_expiration()). The fix is to actually check the ticket expiration instead. I have not created a PR from this branch since I am waiting for my current active PR to be completed. I updated @smhmhmd about this and will create a PR once the current one is closed.

**Comment by saikiranakula-amzn** [comment]
Hi fordth, Thank you for the contribution. We will prioritize reviewing your current active PR

**Comment by fordth** [comment]
> Hi fordth, Thank you for the contribution. We will prioritize reviewing your current active PR

Just an fyi, that change isnt part of my current PR. I told @smhmhmd I will create a separate PR after the current one is complete to include the change mentioned above.

**Comment by gustavo-armenta** [comment]
I ran into this issue. 
The ticket expired on 11/02/23 and the renew until is 11/08/23

Error message when using the ticket
```
[Microsoft][ODBC Driver 17 for SQL Server]SSPI Provider: Ticket expired
[Microsoft][ODBC Driver 17 for SQL Server]Cannot generate SSPI context
```

kerberos ticket state
```
$ klist
Ticket cache: FILE:/var/credentials-fetcher/krbdir/krb5cc
Default principal: gmsa_test$@EXAMPLE.COM

Valid starting     Expires            Service principal
11/01/23 18:38:50  11/02/23 04:38:50  krbtgt/EXAMPLE.COM@EXAMPLE.COM
	renew until 11/08/23 18:38:49
```

the person implementing the fix please add these lines or similar code to support YY and YYYY dates
```
            // if the string is not date time format, return false
            std::string time_fmt = "%m/%d/%Y %T";
            if ( renew_until.length() == 17 ) { time_fmt = "%m/%d/%y %T"; }
            if ( strptime( renew_until.c_str(), time_fmt.c_str(), &tm ) == NULL )
                return false;
```

**Comment by saikiranakula-amzn** [comment]
we are taking a look at it.

**Comment by smhmhmd** [comment]
Thanks @gustavo-armenta 
Would you like to add a code contribution with above change ?
Would be nice if you can also add a small test.

**Comment by fordth** [comment]
@saikiranakula-amzn @smhmhmd @gustavo-armenta  The latest master no longer uses the refresh token expiration but uses the actual token expiration instead.  The latest version I believe addresses your issue as show in the PR that was merged into master just recently. https://github.com/aws/credentials-fetcher/pull/70/files#diff-1e2b010bc984a9143a1d54b5f6c6baf091e52f896db95d10928dc643399122a2

**Comment by smhmhmd** [comment]
@fordth , I think @gustavo-armenta is asking to add another date format in the regex at https://github.com/aws/credentials-fetcher/blob/17b9df0b8e9e5bb59a5cd6fff3d5fc31fa656272/auth/kerberos/src/krb.cpp#L784

**Comment by gustavo-armenta** [comment]
I am using the code from tag v.1.2.0 and running it on ubuntu20
Now, looking at the latest code, I see it changed to use expiration time. 
@fordth is right, the regex needs to change, something like `.+[ ]{2}(.+)[ ]{2}.+`. Then the strptime should support date formats with YY and YYYY

**Comment by fordth** [comment]
@gustavo-armenta  I took both YY and YYYY into account when writing the expression. You can verify this buy running the following RegEx tool here https://regex101.com/r/jW5GZ1/2 using the same regex pattern that credentials-fetcher uses
It uses the ECMAScript regex engine which I believe is the default engine C++ uses

**Comment by gustavo-armenta** [comment]
@fordth try it using the klist output that I shared above in the thread and it does not match correctly

```
# which klist
/usr/local/bin/klist
# /usr/local/bin/klist -V
Kerberos 5 version 1.21.2
# /usr/bin/klist -V
Kerberos 5 version 1.17
# both versions generate same output in ubuntu20
```

**Comment by fordth** [comment]
> Valid starting     Expires            Service principal
> 11/01/23 18:38:50  11/02/23 04:38:50  krbtgt/EXAMPLE.COM@EXAMPLE.COM
> 	renew until 11/08/23 18:38:49

Ok, I see. The regular expression should be .+\n[^\s]+\s+.{8}\s+([^\s]+\s+.{8}).+

As shown here https://regex101.com/r/jW5GZ1/3

**Comment by smhmhmd** [comment]
@gustavo-armenta @fordth 

Could you contribute a PR and a test as well, thanks

**Comment by fordth** [comment]
@smhmhmd Yes I will have a PR in the coming days, we have run into this issue in production as well.  The new regex expression resolves it.

**Comment by saikiranakula-amzn** [comment]
This issue was fixed and deployed in the new release. Closing this issue
