### ISSUE TITLE
parse_options() in config.cpp ignores aws_sm_secret_name parameter passed via command line

### ISSUE THREAD

**Issue by awsjohns** [aws/credentials-fetcher#78]
The logic sets the variable then overrides it later with ECS config:

//snippet where value is retrieved from command line parameters

            case 's':
                cf_daemon.aws_sm_secret_name = optarg;
                std::cout << "Option selected for domainless operation, AWS secrets manager "
                             "secret-name = " << optarg << std::endl;
                break;

//snippet later in function overrides

std::string aws_sm_secret_name = retrieve_secret_from_ecs_config(domainless_gmsa_field);
cf_daemon.aws_sm_secret_name = aws_sm_secret_name;

**Comment by as14692** [comment]
Thank you for opening the issue. We are taking a look at it

**Comment by smhmhmd** [comment]
Fixed [here](https://github.com/aws/credentials-fetcher/commit/40b81fd5177b3f8a5af4001e054abb812745bb98)

**Comment by smhmhmd** [comment]
Fixed [here](https://github.com/aws/credentials-fetcher/commit/40b81fd5177b3f8a5af4001e054abb812745bb98)
