### ISSUE TITLE
Unit Tests are needed to confirm Domainless mode functions

### ISSUE THREAD

**Issue by awsjohns** [aws/credentials-fetcher#79]
Recent commits have broken Domainless mode functionality but went undetected due to lack of unit tests.

**Comment by saikiranakula-amzn** [comment]
looking at it

**Comment by smhmhmd** [comment]
Tests added [here](https://github.com/aws/credentials-fetcher/commit/f54433965dc458014c99cd6ff3dfc0127653dc4e) and [here](https://github.com/aws/credentials-fetcher/commit/1364ea87b949a880134462a0efc77c58beb8a954)

**Comment by smhmhmd** [comment]
[ec2-user@ec2amaz-jp7ful build]$ ./credentials-fetcherd -t
run diagnostic set
krb_files_dir = /var/credentials-fetcher/krbdir
cred_file =  (lease id: fixed_lease_id)
logging_dir = /var/credentials-fetcher/logging
unix_socket_dir = /var/credentials-fetcher/socket
Self test for ticket expiration with 4 digit year is successful
Self test for ticket expiration with 2 digit year is successful
read meta data file test is successful
<2>krb file path contains invalid characters
read invalid metadata test is successful
<2>directory path for kerberos tickets is not provided
krb dir not found test is successful
write meta data info to file test is successful
